### ISSUE TITLE
Undocumented configuration attribute `selectAccount`

### ISSUE THREAD

**Issue by jbean96** [plaid/react-plaid-link#266] opened 2022-06-30 22:39 UTC
I can go into a long winded story of how I figured this out, but there appears to be an undocumented configuration attribute keyed `selectAccount` when using the link token configuration object.

If that key is omitted when creating the config then the Plaid script sends a request to `https://production.plaid.com/link/workflow/start` with the object `link_token_configuration` in the payload containing the attribute `enable_account_select` set to `false`.

If that key is included in the config, the same request sends that attribute set to `true`. 

Notably that attribute does have an effect on the flow in that when the user is authenticated, they are unable/able to select a single account (respectively).

A few questions/concerns stem from that:

1. Should this be documented? It obviously has an effect on the result here.
2. Why is this attribute effecting the flow? I thought that was supposed to be designated based on the link customization as specified in the docs here https://plaid.com/docs/link/customization/#account-select?

**Comment by phoenixy1** [comment] 2023-07-17 17:37
Closing this out as I'm doing a cleanup, but the short story behind the issue is that the attribute was deprecated several years ago, which is why it is present but undocumented. The supported way now to use selectAccount is via configuring a link customization profile via the dashboard.

**Closed by phoenixy1** 2023-07-17 17:37 UTC

**Comment by OscarGodson** [comment] 2023-08-30 20:11
In our case we need different flows for different use cases. I needed to use `selectAccount: true`. Is there a way to setup different flows in the dashboard I missed based on different use cases within the same org?

**Comment by phoenixy1** [comment] 2023-08-30 21:01
@OscarGodson In the Dashboard, you can create multiple different Link customization profiles with different account select settings for different use cases. Then, when calling `/link/token/create`, you would specify which Link customization profile to use for the specific Link session you want to create. For more details, see Link Customizations https://plaid.com/docs/link/customization/ and the `/link/token/create` docs: https://plaid.com/docs/api/tokens/#linktokencreate
