### ISSUE TITLE
Intermittently stops working?

### ISSUE THREAD

**Issue by sarink** [plaid/react-plaid-link#239] opened 2022-02-19 02:49 UTC
I am using the following code
```
export const LinkPlaidItemButton: React.FC<LinkPlaidItemButtonProps> = (props) => {
  const { plaidItemId } = props;
  const isUpdateMode = !!plaidItemId;

  const [linkPlaidItem, { data, loading, error }] = useLinkPlaidItemLazyQuery({
    // Generate a new token every time the button is clicked, an old one could be expired otherwise
    fetchPolicy: 'no-cache',
    variables: { plaidItemId },
  });
  const token = data?.getPlaidLinkToken.linkToken ?? null;
  console.log('got token', token);

  const { open, ready } = usePlaidLink({
    token,
    onEvent: (eventName, metadata) => console.log(eventName, metadata),
    onLoad: () => console.log('link loaded'),
    onExit: (error) => console.log(error),
    onSuccess: () => {}
  });

  useEffect(() => {
    if (token && ready) {
      open();
    }
  }, [token, ready, open]);

  if (error) throw error;

  return (
    <LoadingButton
      variant="contained"
      loading={loading || Boolean(token && !ready)}
      onClick={() => linkPlaidItem()}
    >
      Add Account
    </LoadingButton>
  );
};
```

Occasionally, when launching link in update mode, it just... does nothing. None of the above console logs fire (except the token, which is present), there are no new network requests, it just appears to die. The `ready` state is never fired.

Usually waiting a minute and trying again fixes it. Does anyone know what is going on?

**Comment by neilsanghrajka** [comment] 2022-02-21 04:25
We are experiencing the same. `ready` never resolves to true. On refresh this normally starts working again.

**Comment by sarink** [comment] 2022-02-21 15:54
I ended up writing my own hook that interfaces with `window.Plaid` directly:

```
import { useEffect } from 'react';
import { useScript } from 'src/hooks/useScript';

const PLAID_LINK_STABLE_URL = 'https://cdn.plaid.com/link/v2/stable/link-initialize.js';

export const useAppPlaidLink = (options?: { plaidItemId?: string }) => {
  const plaidItemId = options?.plaidItemId;
  const { loading: scriptLoading, error: scriptError } = useScript(PLAID_LINK_STABLE_URL);

  const [getPlaidLinkToken, { data: tokenData, loading: tokenLoading, error: tokenError }] =
    useGetPlaidLinkTokenLazyQuery({
      fetchPolicy: 'no-cache',
      variables: { plaidItemId },
    });
  const token = tokenData?.getPlaidLinkToken.linkToken ?? null;

  const error = scriptError || tokenError;
  const loading = scriptLoading || tokenLoading;

  useEffect(() => {
    if (!loading && !error && token && window.Plaid) {
      const plaid = window.Plaid.create({
        token,
        onSuccess: async (publicToken, metadata) => {},
      });
      plaid.open();
      return () => plaid.destroy();
    }
  }, [loading, error, token, plaidItemId]);

  if (tokenError || scriptError) throw tokenError || scriptError;

  return {
    error,
    loading,
    open: getPlaidLinkToken,
  };
};
```

**Comment by sarink** [comment] 2022-02-21 16:03
I ended up writing my own hook that calls my api to generate a token and interfaces with `window.Plaid` directly. It's actually quite simple and has been a lot more stable for me than using this lib

For reference:

```
import { useEffect } from 'react';

const PLAID_LINK_STABLE_URL = 'https://cdn.plaid.com/link/v2/stable/link-initialize.js';

export const useAppPlaidLink = (options?: { plaidItemId?: string }) => {
  const plaidItemId = options?.plaidItemId;
  const { loading: scriptLoading, error: scriptError } = useScript(PLAID_LINK_STABLE_URL);

  const [getPlaidLinkToken, { data: tokenData, loading: tokenLoading, error: tokenError }] =
    useLazyQuery(GET_PLAID_LINK_TOKEN, {
      fetchPolicy: 'no-cache',
      variables: { plaidItemId },
    });
  const token = tokenData?.getPlaidLinkToken.linkToken;

  const error = scriptError || tokenError;
  const loading = scriptLoading || tokenLoading;

  useEffect(() => {
    if (!loading && !error && token && window.Plaid) {
      const plaid = window.Plaid.create({
        token,
        onSuccess: (publicToken, metadata) => {
          console.log('success', publicToken, metadata);
        },
      });
      plaid.open();
      return () => plaid.destroy();
    }
  }, [loading, error, token, plaidItemId]);

  return {
    error,
    loading,
    open: getPlaidLinkToken,
  };
};
```

**Comment by neilsanghrajka** [comment] 2022-03-03 14:01
@skylarmb The issue seems to be occurring only with hooks and not the class based component. `ready` never resolves to true intermittently. The hooks documentation and example [here](https://github.com/plaid/react-plaid-link/blob/master/examples/hooks.tsx#L57) recommends waiting till `ready=True` before allowing clicks, but ready does not seem to resolve in many cases. It starts working after refreshing browser window.

We've experienced this very often now.

It looks like the implementation of the class component also does not rely on `ready`, hence seems to be more stable.
https://github.com/plaid/react-plaid-link/blob/master/src/PlaidLink.tsx#L8

**Comment by skylarmb** [comment] 2022-03-03 23:41
hi all @neilsanghrajka @sarink can you clarify which version you are using? 

My gut says this might be something to do with 3.3.0: https://github.com/plaid/react-plaid-link/blob/master/CHANGELOG.md

Can you try downgrading to 3.2.2?

**Comment by skylarmb** [comment] 2022-03-04 00:24
Do you see this warning message if you try to call `open()` in this state?

https://github.com/plaid/react-plaid-link/pull/197/files#diff-29b1325479d1d831fdfad71abb6158e904d9d8394af73e1c3d5884f11bb1d6aeR78-R79

**Comment by sarink** [comment] 2022-03-05 02:32
@skylarmb you can repro with the code in the original post. The `token` is null on some renders and that's intentional, because it isn't available yet.

**Comment by neilsanghrajka** [comment] 2022-03-07 13:13
@skylarmb currently on 3.3.0 , but have previously seen the issue on 3.2.2 as well.
 
Exactly what @sarink said
> The token is null on some renders and that's intentional, because it isn't available yet.

It's definitely more noticeable when the component has multiple renders but i don't have an example to share yet where I can reproduce this consistently

**Comment by Ugikie** [comment] 2022-03-08 19:15
Also experiencing this issue where ready does not resolve to true when using the OAuth flow upon returning back to the page and attempting to reinitialize the link component - it just never opens and internally I can see that "loading" stays true and "iframeLoaded" stays false. Refreshing the page does cause it to work. 

I will try downgrading to 3.2.2

**Comment by vintlucky777** [comment] 2022-03-17 06:29
Hey all!

I found out that having a token that's being resolved async does not work well with `usePlaidLink()` in the same component. If the token has `null` value on initial render, and later resolves into a correct value, `usePlaidLink({ token })` will never return ready state.

As a solution, consider moving the clickable button component and `usePlaidLink()` hook into a separate component, that will only be rendered with a correct token value. While token is loading, render a dummy disabled button.

Alternatively, this helper component may return a simple React Fragment, and just invoke `open()` when ready.

Here's an example based on OPs code:

```jsx

const PlaidLink = ({ token, onEvent, onLoad, onSuccess, onExit }) => {
  const { open, ready } = usePlaidLink({ token, onEvent, onLoad, onExit, onSuccess })
  useEffect(() => {
    if (ready) {
      open();
    }
  }, [ready]);
  return <></>
}

export const LinkPlaidItemButton: React.FC<LinkPlaidItemButtonProps> = (props) => {
  const { plaidItemId } = props;
  const isUpdateMode = !!plaidItemId;

  const [linkPlaidItem, { data, loading, error }] = useLinkPlaidItemLazyQuery({
    // Generate a new token every time the button is clicked, an old one could be expired otherwise
    fetchPolicy: 'no-cache',
    variables: { plaidItemId },
  });
  const token = data?.getPlaidLinkToken.linkToken ?? null;
  console.log('got token', token);

  useEffect(() => {
    if (token && ready) {
      open();
    }
  }, [token, ready, open]);

  if (error) throw error;

  return (
    <>
    <LoadingButton
      variant="contained"
      loading={loading || Boolean(token && !ready)}
      onClick={() => linkPlaidItem()}
    >
      Add Account
    </LoadingButton>
    <PlaidLink
      token={token}
      onEvent={(eventName, metadata) => console.log(eventName, metadata)}
      onLoad={() => console.log('link loaded')}
      onExit={(error) => console.log(error)}
      onSuccess={() => {}}
    />
    </>
  );
};

```

**Comment by skylarmb** [comment] 2022-03-17 21:37
I suspect there is some sort of issue [here](https://github.com/plaid/react-plaid-link/blob/master/src/usePlaidLink.ts#L72) that is causing the `useEffect` internally in react-plaid-link to not re-evaluate the value of `token` or something. If anyone has ideas, im all ears

**Comment by skylarmb** [comment] 2022-03-17 21:39
fwiw the solution @vintlucky777 posted here used to be the **ONLY** way to integrate with this library (we did not accept a null token value). 3.3.0 was supposed to make integration easier by allowing token to be resolved async, but it appears there is something wrong with the logic that none of our internal testing or code samples manages to reproduce or catch

**Comment by skylarmb** [comment] 2022-03-25 01:56
hi all @vintlucky777 @neilsanghrajka @sarink I spent some time today trying to reproduce this with no success. I have no doubt there is an issue here but I think I just need more help identifying what's going on.

What I have tried so far:
- created an example where my component re-renders multiple times while link_token is being generated, and after its generated. result: no issue
- tried the above with update mode as well, also no issue
- tried all of the above using `publicKey` instead of `token`, no issue
- tried `publicKey` with update mode

If there are any hints you have about what your application might be doing that is different than mine, please share!

Here is the sample code I have been using to try to repro: https://github.com/skylarmb/playground-react-plaid-link/blob/sb-troubleshoot-3.3.0/src/App2.tsx

**Comment by AsLogd** [comment] 2022-03-25 15:58
@skylarmb I've been looking into a related issue. In my case, I had two components that used `usePlaidLink`, the second one would never reach ready state. I found out that `react-script-hook` had a bug in `1.5.0` were a second `useScript` hook would not trigger `useEffect`. I could replicate the issue using this code in the `hooks.legacy.js` story.:
```
import React, { useCallback } from 'react';

import { usePlaidLink } from '../src';

const ButtonPlaid = props => {
  const onSuccess = useCallback(
    (token, metadata) => console.log('onSuccess', token, metadata),
    []
  );

  const onEvent = useCallback(
    (eventName, metadata) => console.log('onEvent', eventName, metadata),
    []
  );

  const onExit = useCallback(
    (err, metadata) => console.log('onExit', err, metadata),
    []
  );

  const config = {
    clientName: props.clientName || '',
    env: props.env || 'sandbox',
    product: props.product || ['auth'],
    publicKey: props.publicKey,
    token: props.token,
    onSuccess,
    onEvent,
    onExit,
    // –– optional parameters
    // webhook: props.webhook || null,
    // countryCodes: props.countryCodes || ['US'],
    // language: props.language || 'en',
    // ...
  };
  const { open, ready, error } = usePlaidLink(config);
  console.log('ready ', props.id, ready);
  return (
    <>
      <button
        type="button"
        className="button"
        onClick={() => open()}
        disabled={!ready}
      >
        Open Plaid Link
      </button>
    </>
  );
};

const App = props => {
  return (
    <React.Fragment>
      <ButtonPlaid {...props} id="first" />
      <ButtonPlaid {...props} id="second" />
    </React.Fragment>
  );
};

export default App;
```
After upgrading to `react-script-hook@1.6.0` the issue was fixed. 

If this is the case, then it's possible that the reason this issue is intermitent is because of race conditions in the code (if the hooks gets called first, then it will perform the `useEffect`).

**Comment by skylarmb** [comment] 2022-03-25 17:09
Wow great catch @AsLogd! I will publish a version that bumps `react-script-hook` right away.

**Comment by AsLogd** [comment] 2022-03-25 17:37
@skylarmb any chance on making it compatible with `publicKey`? I think `3.3.0` assumes a token will always be provided. We are using `3.2.2` for this reason and wouldn't be able to benefit from it. 

We can take a look at this in another ticket if needed

**Comment by skylarmb** [comment] 2022-03-25 17:50
@AsLogd yes ill try to slip that in to the patch as well. I would suggest migrating to tokens eventually though. publicKey has been completely deprecated for a few years now

**Comment by AsLogd** [comment] 2022-03-25 17:58
@skylarmb I appreciate it. And sure, I'll remind my team about it haha. Thanks!

**Comment by frenkelor** [comment] 2022-03-31 09:58
Hey, We are having the same issue (recently upgraded from deprecated API to 3.3.0) we are still struggling to reproduce the issue but we are seeing a similar events behavior in our analytics - after refreshing the page issue is being resolved.
Is there a timeline for this fix to be pushed?

**Comment by neilsanghrajka** [comment] 2022-04-04 10:39
@skylarmb Any timelines on when this fix will be deployed?

**Comment by AsLogd** [comment] 2022-04-08 09:47
Looks like we don't have the issue anymore after updating to 3.3.1. From my side this could be closed. Thanks!

**Comment by skylarmb** [comment] 2022-05-09 20:11
Closing this as there are no recent updates and it looks like it was resolved for at least @AsLogd. If anyone else in this thread is still seeing an issue with `ready` state after upgrading to 3.3.1, please feel free to open a new issue.

**Closed by skylarmb** 2022-05-09 20:11 UTC

**Comment by allroundexperts** [comment] 2022-11-03 13:15
@skylarmb This is still an issue for me. I can confirm that the issue lies in the `react-use-scripts` library. Can you update the lib to the latest version? I think that might help.

**Comment by allroundexperts** [comment] 2022-11-03 15:34
@skylarmb Explanation:
https://github.com/hupe1980/react-script-hook/issues/35

**Comment by Ankush1613** [comment] 2024-04-06 06:21
The issue is still. Tried almost all of the solution. Still facing the ussye @skylarmb
