### ISSUE TITLE
button element should have "type='button'" on it

### ISSUE THREAD

**Issue by jeffbarg** [plaid/react-plaid-link#67] opened 2019-11-14 17:39 UTC
When I embed the PlaidLink in a form, it will automatically submit the form since it does not explicitly set type="button" instead of submit.

**Comment by HugoGiraudel** [comment] 2019-11-26 08:42
This is a duplicate of #48.

**Comment by pbernasconi** [comment] 2020-03-18 13:28
Fixed in https://github.com/plaid/react-plaid-link/pull/83

**Closed by pbernasconi** 2020-03-18 13:28 UTC

**Comment by jeffbarg** [comment] 2020-03-18 13:34
Thanks a lot! Really appreciate this :)
