### ISSUE TITLE
Modal not closing on unmount or when calling exit({ force: true }); 

### ISSUE THREAD

**Issue by pipozoft** [plaid/react-plaid-link#242] opened 2022-03-11 04:15 UTC
I'm trying to implement a way to exit Plaid Link when the app times out and the user is logged out, like this:

```ts
const {open, ready, exit} = usePlaidLink(config);
...
useEffect(() => {
  notifications.on('LOG_OUT'], () => {
    exit({force: true}, () => {
      console.log('exit!');
    });
  });

  return () => {
    notifications.remove('LOG_OUT', () => {});
  };
}, []);
```

I have tried both versions` 3.2.2` and `3.3.0` but no luck, the app logs out and navigates to `/login` but the modal stays opened. Any idea why? I read this issue was resolved but I'm still experiencing this issue. Thanks

**Comment by pipozoft** [comment] 2022-03-11 13:48
After some debugging, it looks like when the call to `destroy` never happens in the hook clean up
```ts
// destroy the Plaid iframe factory
return () => next.exit({force: true}, () => next.destroy());
```
here: https://github.com/plaid/react-plaid-link/blob/master/src/usePlaidLink.ts#L71

So if we call destroy in the factory when the `force` option is `true`

```ts
if (exitOptions && exitOptions.force) {
    state.open = false;
    destroy();
  }
```
it works well.

**Comment by skylarmb** [comment] 2022-03-28 18:06
hi all thanks for this report. we are working on a fix for this upstream

**Comment by pipozoft** [comment] 2022-03-29 13:53
@skylarmb thanks for the update!

**Comment by skylarmb** [comment] 2022-04-04 20:04
@pipozoft let me know if the problem is resolved now. This fix shipped a few days ago. If it is not working for you, happy to reopen this issue

**Closed by skylarmb** 2022-04-04 20:04 UTC

**Comment by pipozoft** [comment] 2022-04-05 18:00
@skylarmb thank you! It looks like it's working as expected now 👏
