### ISSUE TITLE
Feature Request - Bank Blocklist

### ISSUE THREAD

**Issue by liplylie** [plaid/react-plaid-link#155] opened 2020-11-04 22:48 UTC
Hi,

For one of my projects, we need functionality where we do not accept certain banks. Is it possible to add a blacklist prop to prevent certain banks from showing?

For now, I just added logic to `onSuccess` to prevent storing data from banks that we are not accepting.

**Comment by skylarmb** [comment] 2020-11-10 22:08
hi @liplylie there is no hidden feature/parameter that you are missing or something. thanks for the feedback! I have added a feature suggestion to our internal product feedback, so i am going to close this for now.

**Comment by skylarmb** [comment] 2020-11-10 22:12
actually looks like we leave feature request issues as Open status. re-opening

**Comment by skylarmb** [comment] 2022-01-28 22:08
Closing this as I have confirmed this is not something Plaid supports and not something we plan to implement.

**Closed by skylarmb** 2022-01-28 22:08 UTC
Labels: feature request
