### ISSUE TITLE
`ready` never resolves to true in 3.3.0

### ISSUE THREAD

**Issue by troyschneringer** [plaid/react-plaid-link#235] opened 2022-02-09 19:19 UTC
Using this component setup the `ready` property no longer resolves to `true` as of 3.3.0...it just stays `false`.  Reverting back to 3.2.2 solved the issue.

```
import Button from '@material-ui/core/Button';
import Box from '@material-ui/core/Box';

import React, { useCallback } from 'react';
import { usePlaidLink } from 'react-plaid-link';

import appConfig from 'helpers/appConfig';

type OwnProps = {
  onSubmit: ({ token: string, plaidId: string }) => void;
}

type Props = OwnProps;

export default function BankAccountForm(props: Props) {
  const { onSubmit } = props;

  const handlePlaidSuccess = useCallback(async (token, metadata) => {
    onSubmit({ token, plaidId: metadata.account_id });
  }, [onSubmit]);

  const config = {
    clientName: [CLIENT NAME]',
    countryCodes: ['US'],
    env: [ENVIRONMENT],
    product: ['auth'],
    publicKey: [PUBLIC KEY],
    onSuccess: handlePlaidSuccess,
  };
  const { open, ready /*, error */ } = usePlaidLink(config);

  return (
    <Box mt={2}>
      <Button variant="outlined" color="primary" size="small" onClick={open} disabled={!ready}>Connect your bank</Button>
    </Box>
  );
}
```

**Comment by troyschneringer** [comment] 2022-02-09 19:27
It seems that commit `ca3a9167db880ba080e2bf77047f7cf0f1f59d33` introduced this is `usePlaidLink.ts` L43-L46.

If a token is not supplied in the options the the `plaid` object is never created.

**Comment by neilsanghrajka** [comment] 2022-02-14 06:32
Facing the same issue.

**Comment by troyschneringer** [comment] 2022-02-14 16:21
@neilsanghrajka I was informed by Plaid support that I should be using `link_tokens` rather than `public_keys` as the later has been deprecated.  Unfortunately this doesn't appear to be a quick change.

It seems to me `3.3.0` introduced a breaking change and should have been indicated in release notes and by bumping the version to `4.0`.  I have reverted back to `3.2.2` for the time being.

**Comment by neilsanghrajka** [comment] 2022-02-14 17:59
@troyschneringer I am using linkTokens and ready still never resolves to true

**Comment by skylarmb** [comment] 2022-03-04 17:46
Great catch all! 3.3.0 does assume you are using `token`s and does not properly account for deprecated public key use case... This is 100% my bad (I often forget that `publicKey` still exists...). Let me think about how to restore public key functionality in 3.3.0, and I will also see if I can debug why even with token that ready still does not resolve to true for some reason.

This is a duplicate of #239 but I will leave both open

**Comment by skylarmb** [comment] 2022-03-04 17:48
For now please use 3.2.2. There are no differences between 3.3.0 and 3.2.2 other than the token behavior, so you aren't missing out on anything.

**Comment by skylarmb** [comment] 2022-03-24 20:53
lets consolidate this thread with #239

**Closed by skylarmb** 2022-03-24 20:53 UTC
