### ISSUE TITLE
"invalid input text length" for a long customer password?

### ISSUE THREAD

**Issue by thomasmost** [plaid/react-plaid-link#274] opened 2022-08-17 17:45 UTC
One of our customers is getting "invalid input text length" when trying to auth their First Republic account. Is this a real limitation of Plaid Link?

They claim their password is 24 characters long—seems like a perfectly reasonable length to me!

![priv_plaid](https://user-images.githubusercontent.com/7980199/185207361-36a32328-b697-4a46-8e77-89a22a3b9da5.png)

**Comment by phoenixy1** [comment] 2023-07-17 17:56
going through old tickets -- i can't reproduce this and don't see any other reports of this, so closing it out as no longer relevant.

**Comment by mckapur** [comment] 2023-08-04 18:29
I was able to reproduce this today

**Comment by phoenixy1** [comment] 2023-08-04 20:11
@mckapur @thomasmost OK, I dug into this a little bit more and here's what I found:
- This only applies to First Republic Corporate (not first republic personal, or most other institutions)
- If you go to the first republic corporate online banking login page at https://corponline.firstrepublic.com/wcmfd/wcmpw/CustomerLogin you will find that the login screen does in fact have a 20-character limit on the password input field 

Therefore, as far as I can tell, Plaid is correctly reflecting a password length limitation set by First Republic. IF customers are seeing this and have a password longer than 20 characters, they are probably trying to log into First Republic Corporate when their account is actually with First Republic Personal.

**Comment by amacrae2** [comment] 2023-08-25 18:36
Hi @phoenixy1, I ran into this issue recently as well. While The First Republic Corporate site (https://corponline.firstrepublic.com/wcmfd/wcmpw/CustomerLogin) appears to limit the number of characters in the password to 20 chars, we were able to prove that if you keep typing additional characters (or use 1password to auto-fill a password of length > 20 chars), the form on the webpage accepts additional characters and the login **will work for passwords longer than 20 chars**, even though the browser visually does not show any characters typed beyond the first 20. Said another way, the truncation of the password is a visual truncation only. For this reason, it is possible to log into the First Republic corporate account with a password of at least 24 characters (this is the length we were able to verify), which then makes it impossible to connect that same account via Plaid due to the 20 character restriction imposed by Plaid.

**Comment by phoenixy1** [comment] 2023-08-25 20:20
@amacrae2 thanks for digging into this! I have got to admit that this seems both very edge casey and at least partially First Republic's fault, but I think you're right that Link shouldn't act this way. 

This doesn't seem specific to react, though, so I'll raise it to the overall link team

**Comment by phoenixy1** [comment] 2023-08-28 16:53
This is now fixed!

**Closed by phoenixy1** 2023-08-28 16:53 UTC
