### ISSUE TITLE
The plaid iframe generates error in console

### ISSUE THREAD

**Issue by alitoshmatov** [plaid/react-plaid-link#305] opened 2023-04-03 14:43 UTC
When plaid view(iframe) opens, plaid api is making request to https://analytics.plaid.com/sentry/api/5/store/ and it is returning with 429 http error code. Based on response message I think the error is originating from sentry service itself.

>Sentry dropped data due to a quota or internal rate limit being reached. This will not affect your application. See https://docs.sentry.io/product/accounts/quotas/ for more information.

The demo( https://plaid.com/demo/ ) also has this problem
<img width="1440" alt="Screenshot 2023-04-03 at 7 43 21 PM" src="https://user-images.githubusercontent.com/59907218/229544282-1a570a92-6091-43c2-855a-a9410432a960.png">

**Comment by phoenixy1** [comment] 2023-07-17 17:30
@alitoshmatov thanks for reporting! I took a look and I can't reproduce this, so I think the issue may have been fixed. If you can still repro let me know, otherwise I'll close this in a few days.

**Comment by phoenixy1** [comment] 2023-07-17 18:15
@alitoshmatov actually, upon reflection, I'm going to close this, since I'm pretty sure it's resolved, but please comment or file a new issue if it is still happening.

**Closed by phoenixy1** 2023-07-17 18:15 UTC
