### ISSUE TITLE
Update on new props

### ISSUE THREAD

**Issue by ryan28561** [plaid/react-plaid-link#42] opened 2019-03-08 23:38 UTC
It appears that the component doesn't update when props are changed. Specifically, I would like to generate a new public token at the time my users hit the page, which means the PlaidLink won't be initialized with the token prop, but I will pass it down once it's loaded. Is it possible to have a ComponentDidUpdate?

**Comment by kevinschaich** [comment] 2019-04-04 00:34
I'm also experiencing this – the component doesn't update in response to parent state changes. Steps to reproduce:

1. Set `publicToken` as a part of the component state
1. Update token in state
1. Click on `PlaidLink`
1. General auth **(NOT update as should happen)** flow proceeds

Minimal example that fails:

```jsx
class TokenStateTest extends React.Component {
  constructor(props) {
    super(props)
    this.state = { token: undefined }
  }

  handleTokenChange = newToken => {
    this.setState({ token: newToken }, () => window.linkHandler.open())
  }

  render = () => {
    return (
      <PlaidLink
        ...
        token={this.state.token}
        ...
      />
    )
  }
}
```

As a workaround, I solved it by generating & opening a new version of the handler on the fly:

```jsx
  ...

  handlePublicTokenChange = newToken => {
    window.Plaid.create({
      clientName: 'My Client',
      env: 'development',
      product: ['auth', 'transactions'],
      key: this.props.config.PLAID_PUBLIC_KEY,
      onExit: this.handleOnExit,
      onSuccess: this.handleOnSuccess,
      token: newToken
    }).open()
  }

  ...
```

But not ideal.

**Comment by ralphsmith80** [comment] 2019-05-27 20:38
I did what @kevinschaich did but utilizing a hooks.

```
const [linkHandler, setLinkHandler] = useState()
useEffect(
    () => {
      if (linkHandler) {
        const plaid = window.Plaid.create({
          clientName: APP_NAME,
          env: PLAID_CONFIG.env,
          product: ['transactions'],
          key: PLAID_CONFIG.publicKey,
          onExit: handleExit,
          onLoad: handleLoad,
          onSuccess: handleSuccess(user, budget),
          token: token,
          webhook: `${APP_URL}/plaidItem`
        })

        if (open) {
          plaid.open()
        }
        if (!open) {
          plaid.exit()
        }
        setLinkHandler(plaid)
      }
    },
    [open, token]
  )
```
The initial `onLoad` needed some special logic since I tied the open prop to a route but if you're not doing that you probably only need ` setLinkHandler(window.linkHandler)`.
```
const handleLoad = () => {
    if (!linkHandler && open) {
      window.linkHandler.open()
    }
    setLinkHandler(window.linkHandler)
  }
```

**Comment by pbernasconi** [comment] 2019-06-10 15:16
Hey @ryan28561  – Sorry that I have been unresponsive for this repo.

In the next few weeks, I'm planning to move this repo over to the official [Plaid](https://github.com/plaid/) organization, and will be addressing this, and the other open issues then!

Stay tuned for an update soon.

**Comment by pbernasconi** [comment] 2020-03-18 13:32
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link

**Closed by pbernasconi** 2020-03-18 13:32 UTC

**Comment by cthomaschase** [comment] 2020-03-20 00:43
Has anyone else tested this using the `usePlaidLink` hook? For me, the linker does not open in `update` mode after a token gets set from prop state.
